[versions]
# Plugins
kotlin = "1.9.20"
kotlinter = "4.1.0"

# Libraries
jgit = "6.8.0.202311291450-r"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[libraries]
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
