[versions]
# Plugins
kotlin = "2.0.20"
kotlinter = "5.0.1"
versions = "0.51.0"

# Libraries
jgit = "7.0.0.202409031743-r"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

[libraries]
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
